#!/usr/bin/env python3
"""Ingest CTD (Comparative Toxicogenomics Database) environmental exposures.

This is THE CRITICAL MISSING PIECE for environmental health queries.

CTD provides:
- Chemical → Gene interactions (e.g., PM2.5 → IL6, Ozone → TNF)
- Environmental exposures → Molecular targets
- Evidence from literature (PubMed IDs)

This fills the gap INDRA doesn't have: environmental → molecular pathways.

Usage:
    python ingest_ctd_environmental.py [--download] [--all]

Options:
    --download  Download latest CTD data first
    --all       Process all chemicals (default: curated environmental exposures)
"""

import argparse
import logging
from pathlib import Path

from converters import ExtendedCSVConverter
from ontology_base import OntologyIngestionPipeline
from parsers import CTDParser, get_parser, OntologyFormat

from ontology_base import CTDDownloader

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

# Paths
SCRIPT_DIR = Path(__file__).parent
DATA_DIR = SCRIPT_DIR / "data"
OUTPUT_DIR = SCRIPT_DIR / "output"

# Curated environmental exposures (CRITICAL for our use case)
ENVIRONMENTAL_CHEMICALS = {
    # Air pollutants
    "Particulate Matter",
    "Ozone",
    "Nitrogen Dioxide",
    "Sulfur Dioxide",
    "Carbon Monoxide",
    # Heavy metals
    "Lead",
    "Cadmium",
    "Arsenic",
    "Mercury",
    # Organic pollutants
    "Benzene",
    "Formaldehyde",
    "Benzo(a)pyrene",
    "Polycyclic Aromatic Hydrocarbons",
    # Reactive species (often generated by pollution)
    "Hydrogen Peroxide",
    "Superoxide",
    "Peroxynitrite",
    # Smoking-related
    "Cigarette Smoke",
    "Nicotine",
    # Dietary/metabolic
    "Glucose",
    "Insulin",
    "Free Fatty Acids",
}


def main():
    parser = argparse.ArgumentParser(
        description="Ingest CTD environmental exposures into KG"
    )
    parser.add_argument(
        "--download", action="store_true", help="Download CTD data first"
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="Process all chemicals (not just environmental)",
    )
    args = parser.parse_args()

    logger.info("=" * 70)
    logger.info("CTD Environmental Exposures → KG Ingestion")
    logger.info("=" * 70)

    # Determine target chemicals
    if args.all:
        logger.info("Mode: ALL chemicals")
        target_chemicals = None  # None = process all
    else:
        logger.info(f"Mode: CURATED ({len(ENVIRONMENTAL_CHEMICALS)} exposures)")
        target_chemicals = ENVIRONMENTAL_CHEMICALS

    # Create pipeline
    pipeline = OntologyIngestionPipeline(
        downloader=CTDDownloader(DATA_DIR),
        parser=CTDParser(),
        converter=ExtendedCSVConverter(),
        target_ids=target_chemicals,
    )

    # Run pipeline
    output_path = OUTPUT_DIR / "ctd_environmental_exposures.csv"

    try:
        num_terms = pipeline.run(download_dir=DATA_DIR, output_path=output_path)

        logger.info("")
        logger.info("✓ SUCCESS: Environmental exposures extracted")
        logger.info(f"  Terms: {num_terms}")
        logger.info(f"  Output: {output_path}")
        logger.info("")
        logger.info("Next steps:")
        logger.info("1. Review extracted chemical → gene interactions")
        logger.info("2. Upload to Writer KG")
        logger.info("3. Query: 'How does PM2.5 affect inflammation?'")
        logger.info("4. System will now find: PM2.5 → IL6, TNF, NF-κB (from CTD)")
        logger.info("5. Then query INDRA: IL6 → CRP, TNF → inflammation")
        logger.info("")
        logger.info("🔗 CRITICAL: This bridges environmental → molecular gap!")

    except Exception as e:
        logger.error(f"✗ Pipeline failed: {e}")
        raise


if __name__ == "__main__":
    main()
