"""Test what chemicals INDRA knows about that might be in environmental exposures.

Strategy: Instead of searching for abstract "PM2.5", search for SPECIFIC chemicals
that are KNOWN to be in air pollution and see if INDRA has pathways for those.

Examples:
- Heavy metals: Lead, Cadmium, Arsenic
- Organic compounds: Benzene, Formaldehyde, PAHs
- Reactive species: Hydrogen peroxide, Peroxynitrite
"""

import asyncio
import logging

from indra_agent.services.indra_production_client import INDRAProductionClient

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)


async def test_chemical_pathways():
    """Test INDRA for specific chemical → molecular pathways."""

    # Chemicals known to be in air pollution
    test_chemicals = [
        # Heavy metals
        "Lead",
        "Cadmium",
        "Arsenic",
        "Mercury",
        # Organic pollutants
        "Benzene",
        "Formaldehyde",
        "Benzo[a]pyrene",  # PAH
        # Reactive species (might be generated by pollution)
        "Hydrogen peroxide",
        "Peroxynitrite",
        "Superoxide",
    ]

    # Target molecular processes
    targets = ["oxidative stress", "NF-κB", "IL6", "CRP", "TNF"]

    async with INDRAProductionClient() as client:
        found_pathways = []

        for chemical in test_chemicals:
            logger.info(f"\nTesting {chemical}...")

            for target in targets:
                try:
                    statements = await client.get_paths_between(
                        [chemical, target], preassemble=True
                    )

                    if statements:
                        logger.info(
                            f"  ✅ FOUND {len(statements)} statements: {chemical} → {target}"
                        )

                        found_pathways.append(
                            {
                                "chemical": chemical,
                                "target": target,
                                "num_statements": len(statements),
                            }
                        )

                        # Show example statement with grounding
                        stmt = statements[0]
                        subj = stmt.get("subj", {})
                        obj = stmt.get("obj", {})

                        logger.info(f"    Example: {subj.get('name')} → {obj.get('name')}")
                        logger.info(f"    Source db_refs: {subj.get('db_refs', {})}")
                        logger.info(f"    Target db_refs: {obj.get('db_refs', {})}")

                except Exception as e:
                    logger.debug(f"  Error querying {chemical} → {target}: {e}")

        logger.info("\n" + "=" * 80)
        logger.info("SUMMARY")
        logger.info("=" * 80)

        if found_pathways:
            logger.info(f"✅ Found {len(found_pathways)} chemical pathways in INDRA:")
            for pw in found_pathways:
                logger.info(
                    f"  {pw['chemical']} → {pw['target']} ({pw['num_statements']} statements)"
                )

            logger.info("\n🔍 CONCLUSION:")
            logger.info(
                "INDRA HAS specific chemical pathways, but NOT abstract environmental terms."
            )
            logger.info(
                "We need to map: 'PM2.5' → {Lead, Cadmium, Benzene, ...} → INDRA pathways"
            )

        else:
            logger.info("❌ No pathways found for tested chemicals.")
            logger.info("May need different chemical names or broader search.")


if __name__ == "__main__":
    asyncio.run(test_chemical_pathways())
